apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-storage.fullname" . }}-secret
  labels:
    {{- include "minio-storage.labels" . | nindent 4 }}
type: Opaque
data:
  rootUser: {{ .Values.auth.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.auth.rootPassword | b64enc | quote }}
