global:
  smtp_smarthost: 'email-mailpit:1025'
  smtp_from: 'alertmanager@infrastructure.local'
  smtp_require_tls: false

route:
  receiver: ops-email
  group_by: ['service', 'alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: ops-critical
      group_wait: 10s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: ops-email
      repeat_interval: 4h

receivers:
  - name: ops-email
    email_configs:
      - to: 'ops-team@infrastructure.local'
        send_resolved: true

  - name: ops-critical
    email_configs:
      - to: 'ops-team@infrastructure.local'
        send_resolved: true
        headers:
          Subject: '🔴 CRITICAL: {{ .GroupLabels.alertname }} ({{ .GroupLabels.service }})'

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['service']
