export default function Home() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>{'{{APP_NAME}}'}</h1>
      <p>Generated by IDP Platform CLI. Edit <code>src/app/page.tsx</code> to get started.</p>
      <p><a href="/api/health">Health Check</a></p>
    </main>
  );
}
