apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alertmanager
  labels:
    app: alertmanager
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: alertmanager
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - name: http
              containerPort: 9093
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 5
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-alertmanager-config
