apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      name: http
  selector:
    app: prometheus
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector:
    app: grafana
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: http
      name: http
  selector:
    app: alertmanager
    release: {{ .Release.Name }}
