apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-headless
  labels:
    app: kafka
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: controller
      port: 9093
      targetPort: controller
  selector:
    app: kafka
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: kafka
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
  selector:
    app: kafka
    release: {{ .Release.Name }}
