apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-platform-api-config
  labels:
    app: platform-api
    release: {{ .Release.Name }}
data:
  PLATFORM_DB_HOST: {{ .Values.env.platformDbHost | quote }}
  PLATFORM_DB_PORT: {{ .Values.env.platformDbPort | quote }}
  PLATFORM_DB_NAME: {{ .Values.env.platformDbName | quote }}
  PLATFORM_DB_USER: {{ .Values.env.platformDbUser | quote }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.env.redisPort | quote }}
  KAFKA_BROKERS: {{ .Values.env.kafkaBrokers | quote }}
  MINIO_ENDPOINT: {{ .Values.env.minioEndpoint | quote }}
  MINIO_PORT: {{ .Values.env.minioPort | quote }}
  KEYCLOAK_URL: {{ .Values.env.keycloakUrl | quote }}
  OPA_URL: {{ .Values.env.opaUrl | quote }}
  KONG_ADMIN_URL: {{ .Values.env.kongAdminUrl | quote }}
