apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kong-proxy
  labels:
    app: kong
    component: proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.proxy.type }}
  ports:
    - port: {{ .Values.proxy.httpPort }}
      targetPort: proxy
      protocol: TCP
      name: http
    - port: {{ .Values.proxy.httpsPort }}
      targetPort: proxy-ssl
      protocol: TCP
      name: https
  selector:
    app: kong
    release: {{ .Release.Name }}
