export const config = {
  platformApi: process.env.PLATFORM_API_URL || 'http://localhost:3020',
  portals: {
    kafka: process.env.KAFKA_PORTAL_URL || 'http://localhost:3001',
    redis: process.env.REDIS_PORTAL_URL || 'http://localhost:3002',
    minio: process.env.MINIO_PORTAL_URL || 'http://localhost:3004',
  },
  tools: {
    kafkaUi: process.env.KAFKA_UI_URL || 'http://localhost:8080',
    redisInsight: process.env.REDIS_INSIGHT_URL || 'http://localhost:5540',
    minioConsole: process.env.MINIO_CONSOLE_URL || 'http://localhost:9001',
  },
  monitoring: {
    kafkaGrafana: process.env.KAFKA_GRAFANA_URL || 'http://localhost:3000',
    redisGrafana: process.env.REDIS_GRAFANA_URL || 'http://localhost:3003',
    minioGrafana: process.env.MINIO_GRAFANA_URL || 'http://localhost:3005',
    kafkaPrometheus: process.env.KAFKA_PROMETHEUS_URL || 'http://localhost:9090',
    redisPrometheus: process.env.REDIS_PROMETHEUS_URL || 'http://localhost:9091',
    minioPrometheus: process.env.MINIO_PROMETHEUS_URL || 'http://localhost:9097',
  },
  services: [
    { name: 'Kafka Broker', port: 9092, server: 'kafka' },
    { name: 'Schema Registry', port: 8081, server: 'kafka' },
    { name: 'REST Proxy', port: 8082, server: 'kafka' },
    { name: 'Kafka UI', port: 8080, server: 'kafka' },
    { name: 'Kafka Portal', port: 3001, server: 'kafka' },
    { name: 'Kafka Grafana', port: 3000, server: 'kafka' },
    { name: 'Kafka Prometheus', port: 9090, server: 'kafka' },
    { name: 'Kafka Alertmanager', port: 9094, server: 'kafka' },
    { name: 'Redis Node 1', port: 6371, server: 'redis' },
    { name: 'Redis Node 2', port: 6372, server: 'redis' },
    { name: 'Redis Node 3', port: 6373, server: 'redis' },
    { name: 'Redis Node 4', port: 6374, server: 'redis' },
    { name: 'Redis Node 5', port: 6375, server: 'redis' },
    { name: 'Redis Node 6', port: 6376, server: 'redis' },
    { name: 'Redis Insight', port: 5540, server: 'redis' },
    { name: 'Cache Portal', port: 3002, server: 'redis' },
    { name: 'Cache Grafana', port: 3003, server: 'redis' },
    { name: 'Cache Prometheus', port: 9091, server: 'redis' },
    { name: 'Cache Alertmanager', port: 9095, server: 'redis' },
    { name: 'MinIO S3 API', port: 9000, server: 'minio' },
    { name: 'MinIO Console', port: 9001, server: 'minio' },
    { name: 'MinIO Node 1', port: 9010, server: 'minio' },
    { name: 'MinIO Node 2', port: 9011, server: 'minio' },
    { name: 'MinIO Node 3', port: 9012, server: 'minio' },
    { name: 'MinIO Node 4', port: 9013, server: 'minio' },
    { name: 'Storage Portal', port: 3004, server: 'minio' },
    { name: 'Storage Grafana', port: 3005, server: 'minio' },
    { name: 'Storage Prometheus', port: 9097, server: 'minio' },
    { name: 'Storage Alertmanager', port: 9098, server: 'minio' },
  ],
};
