apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-portal
  labels:
    app: {{ .Release.Name }}-portal
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-portal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-portal
    spec:
      containers:
        - name: portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-portal-config
          {{- if .Values.sso.enabled }}
          env:
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-portal-sso
                  key: keycloak-issuer
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-portal-sso
                  key: client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-portal-sso
                  key: client-secret
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-portal-sso
                  key: nextauth-secret
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /app/.next/cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}
