{{- if .Values.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-portal-sso
  labels:
    app: {{ .Release.Name }}-portal
type: Opaque
data:
  keycloak-issuer: {{ .Values.sso.keycloakIssuer | b64enc | quote }}
  client-id: {{ .Values.sso.clientId | b64enc | quote }}
  client-secret: {{ .Values.sso.clientSecret | b64enc | quote }}
  nextauth-secret: {{ .Values.sso.nextauthSecret | b64enc | quote }}
{{- end }}
